# Generated by Django 6.0.6 on 2026-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_sale_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
