# Generated by Django 6.0.6 on 2026-06-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stockreduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_address',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_drug_license',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_gst',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_mobile',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('LOST', 'Lost')], max_length=20),
        ),
    ]
