# Generated by Django 6.0.6 on 2026-06-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_sale_customer_address_sale_customer_drug_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='drug_license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
