# Generated by Django 6.0.6 on 2026-06-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_supplier_drug_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='supplier',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
