# Generated by Django 6.0.6 on 2026-06-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_supplier_contact_person_supplier_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
