# Generated by Django 6.0.6 on 2026-07-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_emaillog_emailsettings_emailtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='is_used',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
