# Generated by Django 6.0.6 on 2026-07-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_passwordresetotp_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
