# Generated by Django 6.0.6 on 2026-07-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_passwordresetotp_expires_at_passwordresetotp_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='resend_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
