# Generated by Django 6.0.6 on 2026-07-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_passwordresetotp_resend_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('installed_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
