# Generated by Django 6.0.6 on 2026-07-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_setupotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationstatus',
            name='current_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='installationstatus',
            name='owner_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='installationstatus',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='installationstatus',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='installationstatus',
            name='installed_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='setupotp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
