# Generated by Django 6.0.6 on 2026-07-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_installationstatus_current_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='resend_count',
        ),
    ]
